import { isValidElement } from 'react';
import RootLayout, { metadata } from './layout';

jest.mock('next/font/google', () => ({
  Geist: () => ({ variable: 'font-sans' }),
  Geist_Mono: () => ({ variable: 'font-mono' }),
}));

describe('RootLayout', () => {
  it('exposes metadata for the document', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('builds an html tree with body styling', () => {
    const element = RootLayout({ children: <div>Hello</div> });

    expect(isValidElement(element)).toBe(true);
    if (!isValidElement(element)) return;
    expect(element.type).toBe('html');

    const body = element.props.children;
    expect(isValidElement(body)).toBe(true);
    if (!isValidElement(body)) return;
    expect(body.type).toBe('body');
    expect(body.props.className).toEqual(expect.stringContaining('font-sans'));
    expect(body.props.className).toEqual(expect.stringContaining('font-mono'));
    expect(body.props.className).toEqual(expect.stringContaining('antialiased'));
  });
});
