import { VocabularyItem } from '@/store/useGameStore'

export const SAMPLE_VOCABULARY: VocabularyItem[] = [
  { term: 'สวัสดี', translation: 'Hello' },
  { term: 'ขอบคุณ', translation: 'Thank you' },
  { term: 'ใช่', translation: 'Yes' },
  { term: 'ไม่ใช่', translation: 'No' },
  { term: 'สบายดีไหม', translation: 'How are you' },
  { term: 'แมว', translation: 'Cat' },
  { term: 'หมา', translation: 'Dog' },
  { term: 'น้ำ', translation: 'Water' },
  { term: 'ข้าว', translation: 'Rice' },
  { term: 'รัก', translation: 'Love' },
  { term: 'หนังสือ', translation: 'Book' },
  { term: 'เรียน', translation: 'Study' },
  { term: 'ครอบครัว', translation: 'Family' },
  { term: 'เพื่อน', translation: 'Friend' },
  { term: 'อาหาร', translation: 'Food' },
  { term: 'บ้าน', translation: 'House' },
  { term: 'รถ', translation: 'Car' },
  { term: 'ดอกไม้', translation: 'Flower' },
  { term: 'ต้นไม้', translation: 'Tree' },
  { term: 'ทะเล', translation: 'Sea' },
  { term: 'ภูเขา', translation: 'Mountain' },
  { term: 'ฟ้า', translation: 'Sky' },
  { term: 'ดวงอาทิตย์', translation: 'Sun' },
  { term: 'ดวงจันทร์', translation: 'Moon' },
  { term: 'ดาว', translation: 'Star' },
]
